### ISSUE TITLE
FileLayerProvider: reduce repetitive log

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#233]
Logs are spammed with this message:
"matching feature assets by ID/link title; only single band assets are supported"

Not sure if we can fix root cause, or just avoid that it's not logged on executors? Or use some kind of burst filter...

**Comment by bossie** [comment]
The implementation will look for particular link titles/asset IDs in a feature and compose them into a `BandCompositeRasterSource` that exposes the first band in each of those assets as a band. Essentially, this warning was added to remind us of the limitation that this approach will only work for single band assets and we might have to revisit this in the future.

However, there's nothing that the user can do about this and this warning will only confuse him so I believe we should just remove it from the logs altogether and possibly turn it into a comment instead. Also, the intention was always to only to log it in the driver, not in the executors.

Note that `load_stac` and PROBA-V collections are able to get around this single band limitation because:
- `load_stac` has a mapping of band names to assets/band indices (it relies on `eo:band` properties at the asset level);
- PROBA-V collections are treated as an exception in the code.

**Comment by bossie** [comment]
The log is gone!
