### ISSUE TITLE
Add userid/requestid/correlationid/jobid to logs 

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geotrellis-extensions#64]
openeo-python-driver/openeo-geopyspark-driver injects a couple of ids in the logging from python:
- synchronous req (flask context):  `user_id` (see https://github.com/Open-EO/openeo-python-driver/blob/bfa1acd1ee7d9fbf65037a53a0740bd978a8414f/openeo_driver/util/logging.py#L220-L238) and `req_id` (see https://github.com/Open-EO/openeo-python-driver/blob/bfa1acd1ee7d9fbf65037a53a0740bd978a8414f/openeo_driver/util/logging.py#L162-L205)
- batch job: `user_id` and `job_id`  (see https://github.com/Open-EO/openeo-python-driver/blob/bfa1acd1ee7d9fbf65037a53a0740bd978a8414f/openeo_driver/util/logging.py#L246-L257)

it would be handy if these fields could also be included in the logs from openeo-geotrellis-extentsions (e.g. to be able to get python+java+scala logs from a certain request or user)

**Comment by bossie** [comment]
Might already be implemented in the openeo-logging artifact.

**Comment by bossie** [comment]
The synchronous part is included in #76 (which emphasizes executor logging).

**Comment by bossie** [comment]
Logging of user ID and batch job ID in batch jobs is indeed already covered by the openeo-logging artifact. Much like in the Python code, their values will be treated as global and grabbed from the environment (the batch job driver and executor processes):

![user_id_job_id_in_batch_job](https://user-images.githubusercontent.com/1032518/199539492-1e34c3a9-c1d9-4cea-aa98-ddf0c3a30cbd.png)

**Comment by bossie** [comment]
MDC seems to be the way to include additional properties in log entries, apart from those that the logging framework provides (timestamp, level, filename etc.).

It typically operates by means of a ThreadLocal so a Layout (in Log4j parlance) e.g. JsonLayout is able to fetch and subsequently output user ID/request ID if those are attached to the current thread. This is convenient because this way:
- UID/RID don't have to be passed through the entire call chain;
- they will also be included in log entries not created by us (Spark etc.)

**Comment by bossie** [comment]
The use of ThreadLocal is only reliable if Py4J is configured to use the "pinned thread model" to match Python and Java threads, which, fortunately, is [the default from Spark 3.2 on](https://spark.apache.org/docs/latest/api/python/migration_guide/pyspark_3.1_to_3.2.html).

**Comment by bossie** [comment]
Java now logs user_id and req_id as well in the web app driver:
![scala_sync_logging_driver](https://user-images.githubusercontent.com/1032518/201613210-3eadf993-4715-482e-bb8c-dac3da01a989.png)
