### ISSUE TITLE
allow using custom shub account

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geotrellis-extensions#77]

**Comment by bossie** [comment]
As discussed:
- the use case is e.g. a separate SHub account for VITO users so the account pertains to a particular request rather than an environment (dev/prod/integrationtests)
- batch jobs are most important so it can be implemented with a job_option (the SHub client ID or something that maps to a client ID in case we don't want to expose it)
- Thomas Cassaert should have a vault running where we can fetch the client ID/secret; access to the vault itself is protected by Kerberos

**Comment by bossie** [comment]
Info on the vault: https://confluence.vito.be/display/EP/Vault+setup+and+configuration

**Comment by bossie** [comment]
Given that the rlguard-lib code has to be changed to accommodate for multiple access tokens cached in Zookeeper but we also want to  get rid of rlguard-lib (https://github.com/Open-EO/openeo-geopyspark-driver/issues/216), we could drop rlguard-lib and cache those access tokens in Vault too.

**Comment by bossie** [comment]
The general idea is that we have two sets of credentials:
- default credentials = current SHub OAuth credentials
- VITO credentials = OAuth client ID/secret of new SHub account

We store these KV secrets in Vault with Keycloak as "jwt" authentication method. We then create a policy to allow VITO users "read" access of the VITO credentials. VITO users that use "authenticate_oidc" will then exchange their EGI access token for a Terrascope token with Keycloak and use this token to read the VITO credentials in Vault. Other users will use the default credentials instead.

**Comment by bossie** [comment]
Retrieve default credentials from Vault with Kerberos-authenticated openeo user: https://jira.vito.be/browse/GDD-2240
Retrieve custom credentials from Vault with a Terrascope access token: https://jira.vito.be/browse/GDD-2240

**Comment by bossie** [comment]
Pass this job_option to use a custom account:

```json
{
  "sentinel-hub": {
    "client-alias": "vito"
  }
}
```

This alias (currently: "default" and "vito") is translated to a path in Vault; this way the user is not concerned with specific SHub client IDs and it also allows us to change these client IDs without affecting the user.

**Comment by bossie** [comment]
Token dance in detail at: https://jira.vito.be/browse/GDD-2240

Vault token TTL is something that can be set to an arbitrary value.

**Comment by bossie** [comment]
TODO: get default credentials from Vault with Kerberos-authenticated user openeo.

**Comment by bossie** [comment]
While debugging https://github.com/openEOPlatform/architecture-docs/issues/277, I'm not able to use Postman to retrieve batch processes started with client alias "vito".

Both "default" and "vito" cached credentials point to the same SHub account (geodatadev) - that's not right.

**Comment by bossie** [comment]
CLI login with keytab file (there's no Kerberos support in the Python client):

```
vault login -method=kerberos username=openeo service="vault-prod" realm=VGT.VITO.BE keytab_path=openeo.keytab krb5conf_path=/etc/krb5.conf
```

Pass `-token-only` to make this stateless (just print the Vault token and don't store it on disk).

**Comment by bossie** [comment]
TODO:

- [ ] test
- [ ] merge branch https://github.com/Open-EO/openeo-geopyspark-driver/tree/77_dynamic_default_credentials
- [ ] test again

**Comment by bossie** [comment]
Reverted some commits because they didn't work well with batch job impersonation.

The default credentials now come from a Kerberos-protected secret too. Note that at the moment, a redeploy of the web app is necessary if we change those credentials, for example if they get compromised.

The default and "vito" credentials are respectively in:
- `TAP/big_data_services/openeo/sentinelhub-oauth-default`
- `TAP/big_data_services/openeo/sentinelhub-oauth-vito`
